//! COM feature expansion, ported from `capa/features/com/__init__.py` and
//! `capa/rules/__init__.py::translate_com_feature`.
//!
//! Rule parsing keeps `com/class`/`com/interface` leaves as an opaque
//! `Feature::Com(kind, name)` rather than immediately expanding them into a
//! GUID string/bytes `Or` (see `features.rs`'s `Feature::Com` doc comment),
//! per this project's design of doing that expansion in the matching engine
//! instead. This module is that expansion.
//!
//! The two COM name -> GUID-list databases (`capa/features/com/{classes,
//! interfaces}.py`) are ~3.7k and ~25.6k plain literal Python dicts with no
//! other logic. Rather than reimplementing a Python-literal parser at
//! runtime (or shelling out to Python, which is forbidden -- see AGENTS.md),
//! `scripts/gen_com_db.py` converts them to JSON once; the JSON is embedded
//! here via `include_str!` and parsed lazily on first use.

use std::collections::HashMap;
use std::sync::OnceLock;

use crate::features::{hex_decode, ComKind, Feature, StringFeature};
use crate::rules::{Node, RuleError, Statement};

/// generated by `scripts/gen_com_db.py` from `capa/features/com/classes.py`.
const COM_CLASSES_JSON: &str = include_str!("../data/com_classes.json");
/// generated by `scripts/gen_com_db.py` from `capa/features/com/interfaces.py`.
const COM_INTERFACES_JSON: &str = include_str!("../data/com_interfaces.json");

type ComDatabase = HashMap<String, Vec<String>>;

fn parse_db(json: &str) -> ComDatabase {
    // generated by our own script from a trusted, pinned upstream source;
    // a parse failure here is a build-time packaging bug, not untrusted
    // input, so this is the one place in capa-x allowed to assume success.
    serde_json::from_str(json).unwrap_or_default()
}

/// port of `load_com_database`.
fn load_com_database(kind: ComKind) -> &'static ComDatabase {
    static CLASSES: OnceLock<ComDatabase> = OnceLock::new();
    static INTERFACES: OnceLock<ComDatabase> = OnceLock::new();
    match kind {
        ComKind::Class => CLASSES.get_or_init(|| parse_db(COM_CLASSES_JSON)),
        ComKind::Interface => INTERFACES.get_or_init(|| parse_db(COM_INTERFACES_JSON)),
    }
}

/// port of `COM_PREFIXES`.
fn prefix(kind: ComKind) -> &'static str {
    match kind {
        ComKind::Class => "CLSID_",
        ComKind::Interface => "IID_",
    }
}

fn kind_name(kind: ComKind) -> &'static str {
    match kind {
        ComKind::Class => "class",
        ComKind::Interface => "interface",
    }
}

/// port of the GUID-string -> 16-byte mixed-endian binary encoding inlined
/// in `translate_com_feature`: the first 4 bytes (Data1) and next two 2-byte
/// fields (Data2, Data3) are byte-swapped (little-endian); the trailing 8
/// bytes (Data4) are left as-is.
fn guid_to_bytes(guid: &str) -> Result<[u8; 16], RuleError> {
    let hex_chars: String = guid.chars().filter(|c| *c != '-').collect();
    let raw = hex_decode(&hex_chars)
        .map_err(|_| RuleError::invalid(format!("invalid COM GUID: {guid}")))?;
    let raw: [u8; 16] = raw
        .try_into()
        .map_err(|_| RuleError::invalid(format!("invalid COM GUID: {guid}")))?;
    Ok([
        raw[3], raw[2], raw[1], raw[0], raw[5], raw[4], raw[7], raw[6], raw[8], raw[9], raw[10],
        raw[11], raw[12], raw[13], raw[14], raw[15],
    ])
}

/// port of `translate_com_feature`: expand a `com/class`/`com/interface`
/// leaf into `Or(String(guid) | Bytes(guid_bytes), ...)` across every GUID
/// registered for `com_name`. Errors (rather than silently dropping the
/// rule) if the name isn't in the database, matching upstream's
/// `InvalidRule` at rule-parse time -- ported to RuleSet-build time here
/// since rule parsing defers `Com` leaf expansion to the matching engine.
pub fn translate_com_feature(com_name: &str, kind: ComKind) -> Result<Statement, RuleError> {
    let db = load_com_database(kind);
    let guids = db.get(com_name).filter(|g| !g.is_empty()).ok_or_else(|| {
        RuleError::invalid(format!(
            "'{com_name}' doesn't exist in COM {} database",
            kind_name(kind)
        ))
    })?;

    let symbol = format!("{}{com_name}", prefix(kind));
    let mut children = Vec::with_capacity(guids.len() * 2);
    for guid in guids {
        let guid_bytes = guid_to_bytes(guid)?;
        children.push(Node {
            stmt: Statement::Leaf(Feature::String(StringFeature::Plain(guid.clone()))),
            description: Some(format!("{symbol} as GUID string")),
        });
        children.push(Node {
            stmt: Statement::Leaf(Feature::Bytes(guid_bytes.to_vec())),
            description: Some(format!("{symbol} as bytes")),
        });
    }
    Ok(Statement::Or(children))
}

#[cfg(test)]
#[allow(clippy::unwrap_used, clippy::expect_used)]
mod tests {
    use super::*;

    #[test]
    fn expands_known_class_into_string_and_bytes_or() {
        // ClusAppWiz: ["24F97150-6689-11D1-9AA7-00C04FB93A80"] (capa/features/com/classes.py)
        let stmt = translate_com_feature("ClusAppWiz", ComKind::Class).unwrap();
        let Statement::Or(children) = stmt else {
            panic!("expected Or")
        };
        assert_eq!(children.len(), 2);
        assert_eq!(
            children[0].stmt,
            Statement::Leaf(Feature::String(StringFeature::Plain(
                "24F97150-6689-11D1-9AA7-00C04FB93A80".into()
            )))
        );
        let Statement::Leaf(Feature::Bytes(bytes)) = &children[1].stmt else {
            panic!("expected Bytes leaf")
        };
        // little-endian Data1/Data2/Data3, big-endian Data4
        assert_eq!(
            bytes.as_slice(),
            &[
                0x50, 0x71, 0xF9, 0x24, 0x89, 0x66, 0xD1, 0x11, 0x9A, 0xA7, 0x00, 0xC0, 0x4F, 0xB9,
                0x3A, 0x80
            ]
        );
    }

    #[test]
    fn unknown_com_name_is_a_clean_error() {
        let err = translate_com_feature("ThisDoesNotExist", ComKind::Interface).unwrap_err();
        assert!(err
            .to_string()
            .contains("doesn't exist in COM interface database"));
    }
}
