//! Name-model acceptance: the resolved name list per sample matches a pinned
//! Python
//! dump". The oracle (`capa-x/tests/fixtures/dotnet/name_model.json`) is
//! generated by `scripts/gen_dotnet_name_model.py` against pinned Python
//! `dnfile`/capa (never invoked at test time -- AGENTS.md "No Python at
//! runtime") and committed.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::Deserialize;

use capa_x::extract::dotnet;
use capa_x::extract::dotnet::types::{DnType, DnUnmanagedMethod};

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..")
}

#[derive(Debug, Deserialize, PartialEq, Eq)]
struct OracleDnType {
    token: u32,
    namespace: String,
    class: Vec<String>,
    member: String,
    access: Option<String>,
    #[serde(rename = "str")]
    display: String,
}

#[derive(Debug, Deserialize, PartialEq, Eq)]
struct OracleDnUnmanagedMethod {
    token: u32,
    module: String,
    method: String,
    #[serde(rename = "str")]
    display: String,
}

#[derive(Debug, Deserialize)]
struct OracleSample {
    mixed_mode: bool,
    types: Vec<OracleDnType>,
    managed_imports: Vec<OracleDnType>,
    managed_methods: Vec<OracleDnType>,
    fields: Vec<OracleDnType>,
    unmanaged_imports: Vec<OracleDnUnmanagedMethod>,
}

fn oracle() -> BTreeMap<String, OracleSample> {
    let path = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/dotnet/name_model.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parsing {}: {e}", path.display()))
}

fn to_oracle_shape(t: &DnType) -> OracleDnType {
    OracleDnType {
        token: t.token,
        namespace: t.namespace.clone(),
        class: t.class.clone(),
        member: t.member.clone(),
        access: t.access.map(|a| a.as_str().to_string()),
        display: t.to_string(),
    }
}

fn to_oracle_unmanaged_shape(m: &DnUnmanagedMethod) -> OracleDnUnmanagedMethod {
    OracleDnUnmanagedMethod {
        token: m.token,
        module: m.module.clone(),
        method: m.method.clone(),
        display: m.to_string(),
    }
}

#[test]
fn name_model_matches_pinned_dnfile() {
    let oracle = oracle();
    let corpus_dir = root().join("tests/testfiles/dotnet");

    let mut checked = 0usize;
    for (sample_name, expected) in &oracle {
        let sample_path = corpus_dir.join(sample_name);
        let bytes = std::fs::read(&sample_path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", sample_path.display()));
        let pe = dotnet::load(&bytes).unwrap_or_else(|e| panic!("{sample_name}: parsing: {e}"));

        let mixed_mode = dotnet::is_mixed_mode(&pe)
            .unwrap_or_else(|e| panic!("{sample_name}: is_mixed_mode: {e}"));
        assert_eq!(
            mixed_mode, expected.mixed_mode,
            "{sample_name}: mixed_mode diverges"
        );

        let types: Vec<OracleDnType> = dotnet::types(&pe)
            .unwrap_or_else(|e| panic!("{sample_name}: types: {e}"))
            .iter()
            .map(to_oracle_shape)
            .collect();
        assert_eq!(
            &types, &expected.types,
            "{sample_name}: types diverge from pinned dnfile"
        );

        let managed_imports: Vec<OracleDnType> = dotnet::managed_imports(&pe)
            .unwrap_or_else(|e| panic!("{sample_name}: managed_imports: {e}"))
            .iter()
            .map(to_oracle_shape)
            .collect();
        assert_eq!(
            &managed_imports, &expected.managed_imports,
            "{sample_name}: managed_imports diverge from pinned dnfile"
        );

        let managed_methods: Vec<OracleDnType> = dotnet::managed_methods(&pe)
            .unwrap_or_else(|e| panic!("{sample_name}: managed_methods: {e}"))
            .iter()
            .map(to_oracle_shape)
            .collect();
        assert_eq!(
            &managed_methods, &expected.managed_methods,
            "{sample_name}: managed_methods diverge from pinned dnfile"
        );

        let fields: Vec<OracleDnType> = dotnet::fields(&pe)
            .unwrap_or_else(|e| panic!("{sample_name}: fields: {e}"))
            .iter()
            .map(to_oracle_shape)
            .collect();
        assert_eq!(
            &fields, &expected.fields,
            "{sample_name}: fields diverge from pinned dnfile"
        );

        let unmanaged_imports: Vec<OracleDnUnmanagedMethod> = dotnet::unmanaged_imports(&pe)
            .unwrap_or_else(|e| panic!("{sample_name}: unmanaged_imports: {e}"))
            .iter()
            .map(to_oracle_unmanaged_shape)
            .collect();
        assert_eq!(
            &unmanaged_imports, &expected.unmanaged_imports,
            "{sample_name}: unmanaged_imports diverge from pinned dnfile"
        );

        checked += 1;
    }

    // Guards against a silently-empty oracle passing this test vacuously.
    assert_eq!(
        checked, 8,
        "expected 8 pinned .NET samples, oracle covered {checked}"
    );
}
