//! Metadata-reader acceptance: table row counts for all 8 samples match a
//! committed dump from pinned
//! `dnfile`". The oracle (`capa-x/tests/fixtures/dotnet/table_counts.json`)
//! is generated by `scripts/gen_dotnet_table_counts.py` against pinned
//! Python `dnfile` (never invoked at test time -- the runtime has no Python
//! runtime") and committed.

#![allow(clippy::unwrap_used, clippy::expect_used)]

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use capa_x::extract::dotnet;

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("..")
}

fn oracle() -> BTreeMap<String, BTreeMap<String, usize>> {
    let path =
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/dotnet/table_counts.json");
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    serde_json::from_str(&text).unwrap_or_else(|e| panic!("parsing {}: {e}", path.display()))
}

#[test]
fn table_row_counts_match_pinned_dnfile() {
    let oracle = oracle();
    let corpus_dir = root().join("tests/testfiles/dotnet");

    let mut checked = 0usize;
    for (sample_name, expected) in &oracle {
        let sample_path = corpus_dir.join(sample_name);
        let bytes = std::fs::read(&sample_path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", sample_path.display()));

        let pe = dotnet::load(&bytes)
            .unwrap_or_else(|e| panic!("{sample_name}: parsing CLR metadata: {e}"));
        let actual: BTreeMap<String, usize> = dotnet::table_row_counts(&pe)
            .unwrap_or_else(|e| panic!("{sample_name}: reading table row counts: {e}"))
            .into_iter()
            .map(|(name, count)| (name.to_string(), count))
            .collect();

        assert_eq!(
            &actual, expected,
            "{sample_name}: table row counts diverge from pinned dnfile"
        );
        checked += 1;
    }

    // Guards against a silently-empty oracle passing this test vacuously.
    assert_eq!(
        checked, 8,
        "expected 8 pinned .NET samples, oracle covered {checked}"
    );
}

#[test]
fn looks_like_dotnet_pe_is_true_for_every_pinned_sample() {
    let corpus_dir = root().join("tests/testfiles/dotnet");
    for sample_name in oracle().keys() {
        let sample_path = corpus_dir.join(sample_name);
        let bytes = std::fs::read(&sample_path)
            .unwrap_or_else(|e| panic!("reading {}: {e}", sample_path.display()));
        assert!(
            dotnet::looks_like_dotnet_pe(&bytes),
            "{sample_name}: expected looks_like_dotnet_pe to detect the CLR data directory"
        );
    }
}

#[test]
fn looks_like_dotnet_pe_is_false_for_a_plain_pe() {
    let path = root().join("tests/testfiles/Practical Malware Analysis Lab 01-01.exe_");
    let bytes = std::fs::read(&path).unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    assert!(!dotnet::looks_like_dotnet_pe(&bytes));
}
