//! File-scope fixture parity, generated by `scripts/generate_file_feature_fixtures.py`
//! from the pinned Python capa implementation.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use capa_x::extract::elf_os::detect_elf_os;
use capa_x::extract::strings::{extract_ascii_strings, extract_unicode_strings};
use serde::Deserialize;

fn testfiles_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("tests")
        .join("testfiles")
}

fn fixture(name: &str) -> String {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("file-features")
        .join(name);
    std::fs::read_to_string(&path)
        .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()))
}

#[test]
fn elf_os_matches_python_for_every_elf_testfile() {
    let expected: BTreeMap<String, String> = serde_json::from_str(&fixture("elf-os.json"))
        .unwrap_or_else(|error| panic!("parsing elf-os.json: {error}"));

    assert!(!expected.is_empty(), "ELF OS fixture must not be empty");
    for (relative, expected_os) in expected {
        let path = testfiles_dir().join(&relative);
        let data = std::fs::read(&path)
            .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
        assert_eq!(
            detect_elf_os(&data),
            expected_os,
            "ELF OS mismatch for {relative}"
        );
    }
}

#[derive(Debug, Deserialize, PartialEq, Eq)]
struct ExpectedString {
    value: String,
    offset: usize,
}

#[derive(Debug, Deserialize)]
struct ExpectedStrings {
    ascii: Vec<ExpectedString>,
    utf16le: Vec<ExpectedString>,
}

#[test]
fn strings_match_python_for_five_samples() {
    let expected: BTreeMap<String, ExpectedStrings> =
        serde_json::from_str(&fixture("strings.json"))
            .unwrap_or_else(|error| panic!("parsing strings.json: {error}"));
    assert_eq!(expected.len(), 5, "string fixture must cover five samples");

    for (relative, expected_strings) in expected {
        let path = testfiles_dir().join(&relative);
        let data = std::fs::read(&path)
            .unwrap_or_else(|error| panic!("reading {}: {error}", path.display()));
        let ascii: Vec<_> = extract_ascii_strings(&data, 4)
            .into_iter()
            .map(|value| ExpectedString {
                value: value.s,
                offset: value.offset,
            })
            .collect();
        let utf16le: Vec<_> = extract_unicode_strings(&data, 4)
            .into_iter()
            .map(|value| ExpectedString {
                value: value.s,
                offset: value.offset,
            })
            .collect();

        assert_eq!(
            ascii, expected_strings.ascii,
            "ASCII mismatch for {relative}"
        );
        assert_eq!(
            utf16le, expected_strings.utf16le,
            "UTF-16LE mismatch for {relative}"
        );
    }
}
