//! The schema-parity test:
//! deserialize real `capa -j` output (10 corpus samples, generated by the
//! pinned Python capa via `scripts/difftest.py`'s cache, `-f freeze -j`
//! against `rules/`) into `capa_x::rd::ResultDocument`, re-serialize, and
//! structurally diff against the original -- key order ignored, via
//! `serde_json::Value` equality (a `serde_json::Map` is order-independent
//! for `Eq` unless the `preserve_order` feature is enabled, which this
//! workspace doesn't). Passing this proves the schema field-for-field
//! without hand-checking each one.
//!
//! `deny_unknown_fields` is on every `rd` struct, so a field present in
//! Python's output but missing from our model fails to *deserialize* at
//! all (a hard parse error, not a silent mismatch) -- write this test
//! first, before `from_capa`'s construction logic, per the brief's pitfall
//! note ("the round-trip test in task 1 is what catches these").
//!
//! Regenerating fixtures: see `scripts/difftest.py`'s `ensure_cached`;
//! these files are its `--mode json` reference cache, copied verbatim.

use std::path::Path;

use capa_x::rd::ResultDocument;

fn fixtures_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/resultdoc")
}

fn assert_round_trips(name: &str) {
    let path = fixtures_dir().join(name);
    let original_text = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading fixture {}: {e}", path.display()));

    let doc: ResultDocument = serde_json::from_str(&original_text)
        .unwrap_or_else(|e| panic!("{name}: failed to deserialize into rd::ResultDocument: {e}"));

    let round_tripped = serde_json::to_value(&doc)
        .unwrap_or_else(|e| panic!("{name}: failed to re-serialize: {e}"));
    let original: serde_json::Value = serde_json::from_str(&original_text)
        .unwrap_or_else(|e| panic!("{name}: failed to parse original as JSON: {e}"));

    assert_eq!(
        round_tripped, original,
        "{name}: round-tripped document differs structurally from the original"
    );
}

#[test]
fn pe32_pma01_02() {
    assert_round_trips("pma01-02-exe.json");
}

#[test]
fn pe32_dll() {
    assert_round_trips("e8429581-dll.json");
}

#[test]
fn pe32_driver_sys() {
    assert_round_trips("pma10-03-sys.json");
}

#[test]
fn elf_x86_large() {
    assert_round_trips("elf-x86-294b8d.json");
}

#[test]
fn elf_x86_small() {
    assert_round_trips("elf-x86-bb3814.json");
}

#[test]
fn shellcode32() {
    assert_round_trips("shellcode32-499c2a.json");
}

#[test]
fn shellcode64() {
    assert_round_trips("shellcode64-4b9efd.json");
}

#[test]
fn dotnet() {
    assert_round_trips("dotnet-dd9098.json");
}

#[test]
fn elf_aarch64() {
    assert_round_trips("elf-aarch64-687e79.json");
}

#[test]
fn dynamic_cape_report() {
    assert_round_trips("dynamic-cape-55dcd3.json");
}
